from enum import Enum

class Event(Enum):
    ON_AFTER_RENDER = 0
    ON_BEFORE_RENDER = 1
    ON_APPLICATION_QUIT = 2
    ON_MOUSE0_PRESS = 3
    # This is bad but will do for now
    ROUND_START_SHIP_PLACEMENT = 4
    PLAYER1_FINISHED_PLACING_SHIPS = 5
    PLAYER2_FINISHED_PLACING_SHIPS = 6
    PLAYER1_START_GUESS = 7
    ON_PLAYER1_SUBMIT_GUESS = 8
    PLAYER2_START_GUESS = 9
    ON_PLAYER2_SUBMIT_GUESS = 10
    ON_AFTER_RENDER_BEFORE_DISPLAY = 11
    ON_PYGAME_EVENTS_UPDATE = 12
